version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      python-production-minor-and-patch:
        dependency-type: production
        update-types: [minor, patch]
      python-development-minor-and-patch:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      docker-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
